image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: dashboard
  MYSQL_USER: symfony
  MYSQL_PASSWORD: symfony

before_script:
  - apk add --no-cache docker-compose

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build
  except:
    - tags

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml up -d
    # Replace the following line with your actual test commands
    - echo "Running tests"
    # Example: docker-compose exec php vendor/bin/phpunit
    - docker-compose -f docker-compose.yml down
  except:
    - tags

deploy_to_production:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - master
  environment:
    name: production
    url: 194.164.200.144
  when: manual

